### ISSUE TITLE
generating table chart for frame throws TypeLoadException

### ISSUE THREAD

**Issue by MaciekLesiczka** [fslaborg/zzarchive-FsLab#101]
Hi,
first off, thanks for great data science toolkit.
I started playing with templates you provide and following line causes an exception in interactive console

``` F#
Frame.ofValues [(1,2,3);(4,5,6)] |> Chart.Table
```

> System.TypeLoadException: Could not load type 'Deedle.FSharpFrameExtensions' from assembly 'Deedle, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null'.
>    at XPlot.GoogleCharts.Deedle.Chart.Table.Static[K,V](Frame`2 data, FSharpOption`1 Options)
>    at <StartupCode$FSI_0004>.$FSI_0004.main@()
> Stopped due to error

I tried in both Basic and Journal template, IDE used is VS2013

**Comment by kellerd** [comment]
Related? https://github.com/TahaHachana/XPlot/commit/86077d765c5a2191569f84f3762578b22815536f

As it's now called 
open Deedle.``F# Frame extensions``

https://github.com/TahaHachana/XPlot/issues/31

**Comment by kflu** [comment]
This is still a problem of FsLab, as it depends on the version of xplot (1.3.1) that has this issue. it looks like it's only fixed in a later version of xplot (1.4.1).

I'm not familiar with nuget publishing, but should the fix be changing the dependency version in fslab project?

If someone can suggest the fix, I'm happy to do this.

**Comment by kflu** [comment]
I was able to **work around** this by changing the version number in my paket.lock from 1.3.1 to 1.4.1. But this should **really** be fixed in fslab in order for the journal to work out of the box.

**Comment by tpetricek** [comment]
Hmm, the `Chart.Table` function comes from XPlot and it was never really properly supported. But maybe @TahaHachana knows what is the issue and what we need to get that fixed?

**Comment by TahaHachana** [comment]
1.3.1 opens Deedle.FSharpFrameExtensions instead of Deedle.``F# Frame extensions`` but [I fixed that](https://github.com/TahaHachana/XPlot/issues/31) so it's just a question of updating the XPlot dependencies in FsLab.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
