### ISSUE TITLE
Is there a way to config Deedle table output format

### ISSUE THREAD

**Issue by kflu** [fslaborg/zzarchive-FsLab#117]
It seems that for a large deedle frame, if run in livehtml mode, the embedded table can be scrolled, and there seems to be some javascript that's loading data from the suave server. If it's just exported to static HTML file, most of the rows of the embedded table is ommitted, like so:

![image](https://cloud.githubusercontent.com/assets/1031978/17991413/5df7de44-6af3-11e6-81b1-477e55a7cea0.png)

And even in livehtml, if there're more columns than can be fitted in the width of the page, they're truncated without a horizontal scroll bar.

Can I choose to format the embedded table into a fully loaded, scrollable one? Like the one formatted by IPython notebook:

![image](https://cloud.githubusercontent.com/assets/1031978/17991469/c99669f4-6af3-11e6-846a-0142056a9347.png)

It is more desirable to have something that's **consistent** rather than fancy sometimes (livehtml) and unusable some other times (truncated table in static html).

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
