### ISSUE TITLE
Failed to locate the Zip Header

### ISSUE THREAD

**Issue by khushmeeet** [fslaborg/zzarchive-FsLab#122]
I downloaded FsLab journal template and ran these 2 commands ```chmod +x build.sh``` and ```./build.sh run``` as specified in the website. The process starts installing then NuGet packages but stops at the FAKE package , giving this error. 
<img width="735" alt="screen shot 2016-11-27 at 8 39 47 am" src="https://cloud.githubusercontent.com/assets/8711912/20645253/0c9d732c-b47e-11e6-8d6f-423e30b830c0.png">

I am on macOS sierra. I am totally new to F# and FsLab

**Comment by tpetricek** [comment]
This looks like an issue in Paket (http://github.com/fsprojects/Paket), the package manager we're using in FsLab. Can you check what version of mono are you using? Also, does this happen reproducibly? (It could be just a network error...)

**Comment by Khushmeet** [comment]
Mono version is 4.6.2 .
I  tried several times, but it results in same error. I even downloaded the template again. I don't think its a network error.
Template is FsLab journal.

**Comment by forki** [comment]
Usually all zip issues go away by updating mono to whatever is latest and greatest. 

Please also try to run "paket clear-cache" since the download might actually be corrupted

**Comment by Khushmeet** [comment]
I will try that!

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
