### ISSUE TITLE
How to embed FSharp.Charting chart images in the generated HTML?

### ISSUE THREAD

**Issue by kflu** [fslaborg/zzarchive-FsLab#123]
This is an issue with FSharp.Charting only, Xplot doesn't have the problem. The problem is that a chart generated by FSharp.Charting seems to be served via a local webserver, rather than a static image file on the disk. The problem with that is when I want to export the fslab journal as a static HTML file, all the image links are broken - as the local web server isn't running. 

How to fix this problem?

**Comment by kflu** [comment]
I'm attempting to fix this with https://github.com/fslaborg/FsLab.Formatters/pull/3/commits/8c2d979c953dd7162e2e5453786ab54182eda55a

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
