### ISSUE TITLE
Fslab journal frustration for novices

### ISSUE THREAD

**Issue by hodzanassredin** [fslaborg/zzarchive-FsLab#128]
I decided to try to move some of my pandas ipy notebooks into fslab journal. Unfortunately, there are a lot of troubles for beginners.

My environment: windows 10 with vs2017(with fsharp)

Download
=======
After download, nothing is going to work due to fake's error mentioned [here](https://github.com/fsharp/FAKE/issues/1372) and incorrect FSharp.Core.dll version

![default](https://cloud.githubusercontent.com/assets/40375/26779208/316b2d48-49ed-11e7-8262-da2f75abe778.png)

Code
====

Fixed bugs and wrote some incorrect code:
 
```
let f = Frame.ReadCsv(@"some.csv")
let flat2Darray arr = ...
let data = f.ToArray2D()
(*** include-value:data ***)
(*** define-output:chart ***)
Chart.StackedColumn (data |> flat2Darray)
(*** include-it:chart ***)
```
Error:

>  Exception =
>   FsiEvaluationException:
> 
> Error:
> 
>         input.fsx(1,22): error FS0039: The value or constructor 'data' is not defined
> 
> 
> Output:
> 
> Input: Chart.StackedColumn (data |> flat2Darray)
> 
> Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System
> Exception: Operation failed. The error text has been print the error stream. To return the corresponding FSharpErrorInf
>  use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
>    at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res) in C:\User
> \robin\dev\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2418
>    at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalInteraction(String code) in C:\Users\robin\d
> v\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2540
>    at Yaaf.FSharp.Scripting.Helper.evalInteraction@1095.Invoke(String arg00) in c:\Tomas\Public\tpetricek\FSharp.Format
> ing\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1095
>    at Yaaf.FSharp.Scripting.Helper.save_@1072-2.Invoke(Unit unitVar0) in c:\Tomas\Public\tpetricek\FSharp.Formatting\pa
> et-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1073
>    at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in c:\Tomas\Public
> tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScript
> ng.fs:line 1018
>    at Yaaf.FSharp.Scripting.Helper.redirectOut@1044[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err,
> FSharpFunc`2 f) in c:\Tomas\Public\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaa
> .FSharp.Scripting\YaafFSharpScripting.fs:line 1051
>    at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in c:\Tomas\Public\tpetricek\FSharp.Formatting\pake
> -files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1072
>    --- End of inner exception stack trace ---
>    at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in c:\Tomas\Public\tpetricek\FSharp.Formatting\pake
> -files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1080
>    at Yaaf.FSharp.Scripting.Helper.session@1100.Yaaf-FSharp-Scripting-IFsiSession-EvalInteractionWithOutput(String ) in
> c:\Tomas\Public\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\
> aafFSharpScripting.fs:line 1101
>    at <StartupCode$FSharp-Literate>.$Evaluator.FSharp-Literate-IFsiEvaluator-Evaluate@158.Invoke(Unit unitVar0) in c:\T
> mas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Evaluator.fs:line 163
>    at Yaaf.FSharp.Scripting.Extensions.IFsiSession.WithCurrentDirectory[b](IFsiSession x, String dir, FSharpFunc`2 f) i
>  c:\Tomas\Public\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting
> YaafFSharpScripting.fs:line 552
>    at FSharp.Literate.FsiEvaluator.FSharp-Literate-IFsiEvaluator-Evaluate(String text, Boolean asExpression, FSharpOpti
> n`1 file) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Evaluator.fs:line 152;
>  StdErr =
>   "
> 
> input.fsx(1,22): error FS0039: The value or constructor 'data' is not defined
> ";}

As a novice I'm not able to understand wtf is going on and VS doesnt show any errors inside editor screen. And there were some additional errors with compiler services and it forces me to restart journal everytime. Unfortunately now I'm not able to reproduce them.

Charting
======

I decided to build stacked bar chart(based on Tutorial.fsx). And found documentation [here](https://fslab.org/FSharp.Charting/reference/fsharp-charting-chart.html). But Intellisence shows only some basic charts (static members of Chart) and it is not trivial to understand where are funnel and stacked charts. (finally I found that I have to add #I "packages/FSharp.Charting" #load "FSharp.Charting.fsx")

Next problem is to find an example of stacked chart. Only page which I found have some problems in layout. [here](https://fslab.org/FSharp.Charting/FurtherSamples.html) ![default](https://cloud.githubusercontent.com/assets/40375/26779135/ec562992-49ec-11e7-8248-d4b3a585bc03.png)

Actually all other docs for fsharp charting contain some strange code in footer.
![default](https://cloud.githubusercontent.com/assets/40375/26779171/ff080060-49ec-11e7-8ac5-6340ef9ce539.png)

Final question was about how to use dataframe to build a chart. Charting lib expects input as seq of seqs of tuples. And there is no helper methods to do it in a fast way.

**Comment by hodzanassredin** [comment]
Reproduced additional bug.
The dumb code

```
#load "packages/FsLab/Themes/DefaultWhite.fsx"
#load "packages/FsLab/FsLab.fsx"
#I "packages/FSharp.Charting"
#load "FSharp.Charting.fsx"

open FSharp.Charting
(**

Welcome to FsLab journal
========================

FsLab journal is a simple Visual Studio template that makes it easy to do
interactive data analysis using F# Interactive and produce nice HTML or PDF
to document you research.

Next steps
----------

 * If you are using Visual Studio template, go to "Solution Explorer", right click
   on your newly created project, select "Add", "New item.." and choose
   "FsLab Walkthrough". This contains addtional examples you can explore.

 * To add new experiments to your project, just clone this file and rename it.
   In Visual Studio, you can got to "Add", "New item" and choose
   new "FsLab Experiment". You can have multiple scripts in a single project.

 * To see how things work, run `build run` from the terminal to start the journal
   runner in the background (or hit **F5** in Visual Studio). FsLab Journal will
   turn this Markdown document with simple F# script into a nice report!

 * To generate PDF from your experiments, you need to install `pdflatex` and
   have it accessible in the system `PATH` variable. Then you can run
   `build pdf` in the folder with this script (then check out `output` folder).

Sample experiment
-----------------

We start by referencing `Deedle` and `FSharp.Charting` libraries and then we
load the contents of *this* file:
*)

(*** define-output:loading ***)
open Deedle
open System.IO
open XPlot.GoogleCharts
open XPlot.GoogleCharts.Deedle
open System

let f = Frame.ReadCsv(@"D:\migrate\bright\dcs\dcs_ret.csv")
let flat2Darray (array2D : float[,]) = 
                seq { for x in [0..(Array2D.length1 array2D) - 1] do 
                        yield seq{
                          for y in [0..(Array2D.length2 array2D) - 1] do 
                              yield float(y), array2D.[x, y] } |> List.ofSeq
                        } |> List.ofSeq
(*** include-value:f ***)
let data = (f.Transpose().ToArray2D<float>() |> flat2Darray)
let row = data.[0-100]
(*** include-value:row ***)
(**
Now, we split the contents of the file into words, count the frequency of
words longer than 3 letters and turn the result into a Deedle series:
*)

(**
We can take the top 5 words occurring in this tutorial and see them in a chart:
*)
(*** define-output:grid ***)

(*** include-it:grid ***)
(**
Finally, we can take the same 6 words and call `Chart.Column` to see them in a chart:
*)

(*** define-output:chart ***)

Chart.Line (row)
(*** include-it:chart ***)

(*** define-output:chart ***)

Chart.StackedColumn (f.Transpose().ToArray2D<float>() |> flat2Darray)
(*** include-it:chart ***)

(**
Summary
-------
An image is worth a thousand words:

![](http://imgs.xkcd.com/comics/hofstadter.png)
*)
```

And result:

> Generating 'Tutorial.html'
> Tutorial.fsx was changed.
> 
> Unhandled Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while creating a fsi session. ---> System.Excep
> tion: Error creating evaluation session: StopProcessingExn None
>    at Microsoft.FSharp.Compiler.Interactive.Shell.-ctor@2373-120.Invoke(String message) in C:\Users\robin\dev\FSharp.Com
> piler.Service\src\fsharp\fsi\fsi.fs:line 2373
>    at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[
> ] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible) in C:\Users\robin\dev
> \FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2373
>    at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig,
> String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible) in C:\User
> s\robin\dev\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2626
>    at Yaaf.FSharp.Scripting.Helper.fsiSession@1057.Invoke(Unit unitVar0) in c:\Tomas\Public\tpetricek\FSharp.Formatting\
> paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1058
>    at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in c:\Tomas\Public\
> tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripti
> ng.fs:line 1018
>    at Yaaf.FSharp.Scripting.Helper.redirectOut@1044[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err,
> FSharpFunc`2 f) in c:\Tomas\Public\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf
> .FSharp.Scripting\YaafFSharpScripting.fs:line 1051
>    at Yaaf.FSharp.Scripting.Helper.getSession(Object fsi, FsiOptions options, Boolean reportGlobal, FSharpOption`1 liveO
> ut, FSharpOption`1 liveOutFsi, FSharpOption`1 liveErr, FSharpOption`1 liveErrFsi, Boolean preventStdOut) in c:\Tomas\Pub
> lic\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScr
> ipting.fs:line 1057
>    --- End of inner exception stack trace ---
>    at Yaaf.FSharp.Scripting.Helper.getSession(Object fsi, FsiOptions options, Boolean reportGlobal, FSharpOption`1 liveO
> ut, FSharpOption`1 liveOutFsi, FSharpOption`1 liveErr, FSharpOption`1 liveErrFsi, Boolean preventStdOut) in c:\Tomas\Pub
> lic\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScr
> ipting.fs:line 1063
>    at Yaaf.FSharp.Scripting.ScriptHost.Create(FsiOptions opts, FSharpOption`1 fsiObj, FSharpOption`1 reportGlobal, FShar
> pOption`1 outWriter, FSharpOption`1 fsiOutWriter, FSharpOption`1 errWriter, FSharpOption`1 fsiErrWriter, FSharpOption`1
> preventStdOut) in c:\Tomas\Public\tpetricek\FSharp.Formatting\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.
> FSharp.Scripting\YaafFSharpScripting.fs:line 1263
>    at FSharp.Literate.FsiEvaluator..ctor(FSharpOption`1 options, FSharpOption`1 fsiObj) in c:\Tomas\Public\tpetricek\FSh
> arp.Formatting\src\FSharp.Literate\Evaluator.fs:line 106
>    at FsLab.Runner.createFsiEvaluator(ProcessingContext ctx) in C:\Tomas\Public\fslaborg\FsLab\src\FsLab.Runner\Runner.f
> s:line 153
>    at FsLab.Runner.processScriptFiles(Boolean overwrite, ProcessingContext ctx) in C:\Tomas\Public\fslaborg\FsLab\src\Fs
> Lab.Runner\Runner.fs:line 203
>    at FSI_0005.Build.handleWatcherEvents(FileSystemEventArgs e) in C:\Users\hodza\Desktop\FsLab.Templates-journal\build.
> fsx:line 84
>    at FSI_0005.Build.clo@126-28.Invoke(RenamedEventArgs e) in C:\Users\hodza\Desktop\FsLab.Templates-journal\build.fsx:l
> ine 126
>    at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable@2172.System-IObserver`1-OnNext(T value)
>    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.h@758.Invoke(Object _arg1, TArgs args)
>    at FSI_0005.Build.clo@126-27.Invoke(Object sender, RenamedEventArgs e) in C:\Users\hodza\Desktop\FsLab.Templates-jour
> nal\build.fsx:line 126
>    at System.IO.FileSystemWatcher.OnRenamed(RenamedEventArgs e)
>    at System.IO.FileSystemWatcher.NotifyRenameEventArgs(WatcherChangeTypes action, String name, String oldName)
>    at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappe
> dPointer)
>    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverla
> pped* pOVERLAP)
> PS C:\Users\hodza\Desktop\FsLab.Templates-journal>

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
