### ISSUE TITLE
Creating PDF fails using the template out of the box

### ISSUE THREAD

**Issue by halcwb** [fslaborg/zzarchive-FsLab#145]
Trying to create a PDF fails using the out of the box template project.

Example: 

```
dotnet new fslab.journal testfslab
cd testfslab
./build pdf
```

Fails with: 

> 
> The running order is:
>   - pdf
> Running build with 1 worker
> Starting Target: pdf
> packages/FSharp.Literate.Scripts/tools/fsx2html.exe --pdf --watch (in C:\Development\lab\testfslab)
> Reading scripts from 'C:\Development\lab\testfslab'
> Writing output to 'C:\Development\lab\testfslab\output'
> 
> unhandled exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Tool.exec(Boolean shell, String workingDir, String exe, String args)
>    at Tool.main(String[] argv)
> fsx2html.exe --pdf --watch failed

Info:

> 
> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.103
>  Commit:    8edbc2570a
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.1.7601
>  OS Platform: Windows
>  RID:         win7-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.2.103\
> 
> Host (useful for support):
>   Version: 2.2.1
>   Commit:  878dd11e62
> 
> .NET Core SDKs installed:
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   2.1.101 [C:\Program Files\dotnet\sdk]
>   2.2.103 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by drk-mtr** [comment]
Within the generated .fsx file in the example it states:

 * To generate PDF from your experiments, you need to install `pdflatex` and
   have it accessible in the system `PATH` variable. Then you can run
   `build pdf` in the folder with this script (then check out `output` folder).

I'm installing it now, after ending up here because I didn't spot this note either. My own fault really, but a brief mention on the `fslab.org/download` page might be a nice addition.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
