### ISSUE TITLE
RProvider is not working anymore

### ISSUE THREAD

**Issue by halcwb** [fslaborg/zzarchive-FsLab#146]
- Use the template out of the box. 
- Install R 3.4.3 (not the latest version)
- Uncomment the RProvider section in the paket.dependencies 
- Install using paket
- Try to load the RProvider.fsx

Results in:

See attachement
[rprov_log.txt](https://github.com/fslaborg/FsLab/files/3077216/rprov_log.txt)

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
