### ISSUE TITLE
nuget package dependencies are not >= but =

### ISSUE THREAD

**Issue by jkone27** [fslaborg/zzarchive-FsLab#150]
Hello, i assume package dependencies should be >= to ensure good integration with other libs and upgraded lib versions, not = ?

![image](https://user-images.githubusercontent.com/10419217/75626119-f1ff9d00-5bc4-11ea-968f-b05a4d121741.png)

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
