### ISSUE TITLE
Only web locations are supported on the PCL versions of F# Data?

### ISSUE THREAD

**Issue by halcwb** [fslaborg/zzarchive-FsLab#153]
Trying to get a simple CSV provider to work on my Mac results in an error:

`System.Exception: Only web locations are supported on the PCL versions of F# Data. Please use the full .NET version instead.S`

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
