### ISSUE TITLE
Create a sample.fsx to be automatically included into the project when adding the nuget package

### ISSUE THREAD

**Issue by ovatsus** [fslaborg/zzarchive-FsLab#2]
something like

```
#load "packages/FsLab-xx/FsLab.fsx"
// Small Deedle example
// Small FSharp.Data example
// Small RProvider example
```

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
