### ISSUE TITLE
Support Visual Studio 2012

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#23]
I think there is nothing that makes it impossible to support VS 2012. The template needs to be modified to restore NuGet packages in VS2012, but otherwise it should work.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
