### ISSUE TITLE
Add some form of "publish to web"

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#25]
This might be done by making the template a web project [and using the upcoming publish-to-web](http://blogs.msdn.com/b/fsharpteam/archive/2014/04/06/towards-web-project-support-in-the-visual-f-tools.aspx).

Alternative approach would be to have some our hosting for FsLab notebooks similar to the IPython notebook viewer. 

This is `up-for-grabs`, but please start a discussion here first to plan what would be the best way to do this.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
