### ISSUE TITLE
Support breakpoints in script file

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#28]
When you hit `F5`, it would be nice if you were able to debug the scripts.
- The FSharp.Compiler.Service already generates debug symbols and information for scripts that it receives, so in principle this is possible.
- There may, however  be sensitivity to the paths used, for example if you copy or transform the scripts, or if you don’t use fully-qualified paths.  One way around this may be to use line directives like FsYacc and FsLex (if you have a transformation step).

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
