### ISSUE TITLE
Notebook fails when R package "zoo" is not installed

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#34]
See also: https://github.com/BlueMountainCapital/Deedle/issues/143

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
