### ISSUE TITLE
Standalone nuget package

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#4]
Package restore breaks when used from Linux or command line, so it would be nice to have `FsLab.Standalone` which contains all dlls in a single folder and does not need powershell scripts.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
