### ISSUE TITLE
How to process *.fsx script and pass parameters to it?

### ISSUE THREAD

**Issue by sergey-tihon** [fslaborg/zzarchive-FsLab#40]
Is there any way to pass parameters for `*.fsx` script through `Literate.ParseScriptFile`?

I want to use the same `*.fsx` file to generate multiple notebooks that calculated base on different data sets. So I need to pass information about data set.

I have tried to do it using temp config file near the script, but I have faced the issue that `__SOURCE_DIRECTORY__` have the strange value when `Literate.ParseScriptFile` executes script. Finally I hard-coded path to the file with parameters.

Is there a better way to do it?

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
