### ISSUE TITLE
Load dataframe from table

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#52]
Say you have a table in your Markdown with sample data: https://github.com/tpetricek/FSharp.Formatting/pull/9

It would be nice if you were able to load it into a Deedle frame.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
