### ISSUE TITLE
Add  Accord.NET

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#53]
It would be nice to add support for this with
- Support vector machines etc.
- Logistic regression etc.

One thing is to add a nice F#-friendly wrapper. Another thing is to add Deedle integration.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
