### ISSUE TITLE
There should be an easy way to convert CSV type providers to deedle data frames

### ISSUE THREAD

**Issue by forki** [fslaborg/zzarchive-FsLab#6]
This would be 

![code-35](https://f.cloud.github.com/assets/57396/1695933/c609a816-5eba-11e3-9b14-750a1c8692b5.gif)

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
