### ISSUE TITLE
Template location

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#62]
Why are we under root "Visual F# Items" node?

![items](https://cloud.githubusercontent.com/assets/485413/5859437/1aba8840-a252-11e4-8c26-b3e3ab54e3a2.png)

Ideally, we would like to have "Visual F# Items/FsLab" or something (akin to "Visual F# Items/Data") or something like this.

**Comment by cdrnet** [comment]
...and why is there a Visual F# Items within Visual F# Items?

**Comment by tpetricek** [comment]
I think FsLab may be causing this somehow with its templates... huh

**Comment by cdrnet** [comment]
For some reason it looks a bit better on my system.

![fslab-newitem](https://cloud.githubusercontent.com/assets/47147/5862194/04144b62-a270-11e4-9ca3-2c14ce0cce93.png)

But an FsLab folder would be nice. Maybe we can use [ProjectSubType](https://msdn.microsoft.com/en-us/library/ms171386.aspx) for that, as Dan does for the [MVC templates](https://github.com/dmohl/FSharpMVC3Starter/blob/master/FSMVC3.vstemplate).

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
