### ISSUE TITLE
parameterize index.html header

### ISSUE THREAD

**Issue by TonyAbell** [fslaborg/zzarchive-FsLab#73]
Header for index.html is set in [FsLab.Runner](https://github.com/tpetricek/FsLab/blob/master/src/FsLab.Runner/Runner.fs#L212-215) 

This should be parameterized so it can be passed in [here](https://github.com/tpetricek/FsLab/blob/master/src/journal/Main.fs)

**Comment by tpetricek** [comment]
That would be great addition!

**Comment by 5aumy4** [comment]
Hello people!
Is this issue open?
And if it is , can I fix it?

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
