### ISSUE TITLE
parameterize which scripts get run

### ISSUE THREAD

**Issue by TonyAbell** [fslaborg/zzarchive-FsLab#74]
Any `.fsx` or `.md` will be parsed to generate documentation by [this](https://github.com/tpetricek/FsLab/blob/master/src/FsLab.Runner/Runner.fs#L162-167)

It would be nice to exclude scripts that are not done, or include just the one I am working on.

If a `whitelist` of scripts was passed into the [Runner](https://github.com/tpetricek/FsLab/blob/master/src/journal/Main.fs) we could also pass in parameters to the script to address this issue tpetricek/FsLab/issues/40

For Example

```
  let p = Map.empty<string,string>
  let whiteList = [("script1.fsx", p); ("script2.fsx", p)]
  Journal.Process(browse,scripts=whieList)
```

**Comment by tpetricek** [comment]
A design with a whitelist/blacklist for skipping unfinished scripts sounds good. 

As for the parameterization, this is an interesting problem - how would the script access the parameters?

**Comment by TonyAbell** [comment]
Would this [Mixin Type Provider](http://pinksquirrellabs.com/post/2015/03/01/Introducing-The-Mixin-Type-Provider.aspx) will help with this feature

**Comment by tpetricek** [comment]
I don't think that's really useful here. I suppose the script could just access the parameters via some global dictionary. It is not particularly elegant, but it would be fairly easy to support something like:

    Journal.Process(browse, parameters=["foo", 42])

And then in the scripts, you could write:

    let n = unbox<int> (FsLab.Parameters.["foo"])

I suppose we could make this a lot fancier using type providers, but I'm not sure if that's necessarily needed in the first version. Are there similar tools in R/elsewhere that let you do something like this?

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
