### ISSUE TITLE
Output a Sequence of charts as a gallery of Images for html output

### ISSUE THREAD

**Issue by damageboy** [fslaborg/zzarchive-FsLab#75]
I think it would be useful to support galleries of charts.
i.e. if I have an expression that creates multiple charts, it would output multiple png files for all of those charts, and display them, at least for html output withsomething like:

http://www.jssor.com/demos/image-gallery-with-vertical-thumbnail.html

Does this sound acceptable?

What should happen for other outputs? Just a series of charts?

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
