### ISSUE TITLE
Use the new FAKE watcher

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#88]
See: https://github.com/fsprojects/Paket/pull/811
Also, do the change in: https://github.com/fslaborg/FsLab.Templates

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
