### ISSUE TITLE
Caching of results in Journal

### ISSUE THREAD

**Issue by evelinag** [fslaborg/zzarchive-FsLab#94]
It would be great if FsLab could cache computed results in a Journal so that they are not repeated every time the Journal is recompiled. Something similar to the `cache` option in R package [knitr](http://yihui.name/knitr/demo/cache/).

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
